scheduler.jdbc.thread-pool-size: 10
spring:
  profiles:
    active: local
  application:
    name: parking-api
  datasource:
    url: jdbc:mysql://localhost:3306/dbParking?useSSL=false
    username: parkingUser
    password: parkingPass
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
    locations: classpath:db/migration
