server.port: 8080
scheduler.jdbc.thread-pool-size: 10
spring:
  profiles:
    active: local
  application:
    name: parking-api
  datasource:
    url: ${MYSQL_DATABASE:jdbc:mysql://localhost:3306/dbParking?useSSL=false}
    username: ${MYSQL_USER:parkingUser}
    password: ${MYSQL_PASS:parkingPass}
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
    locations: classpath:db/migration
